### ISSUE TITLE
allow_url_fopen usually cannot be enabled on hosted websites

### ISSUE THREAD

**Issue by palatinuse** [amiyasahu/q2a-bootstrap-recaptcha#1]
This plugin needs the allow_url_fopen option to be enabled in the server's config, which is usually disabled by the hosting provider of the website. 

Is there a way to configure this plugin to use curl instead?

**Comment by amiyasahu** [comment]
This is an older plugin which uses an older version of recaptcha , Not sure if we can use some different way . 

Best way to deal with this is to use the newer plugin which comes with the q2a by default - https://github.com/q2a/question2answer/tree/dev/qa-plugin/recaptcha-captcha

You can follow the instructions here for more information on this issue - https://github.com/google/recaptcha/issues/36

**Comment by palatinuse** [comment]
The version shipped with q2a by default has the same issue.
The google post mentions features that are not included in the recaptcha version shipped with q2a.

**Comment by amiyasahu** [comment]
I will check on this ..

**Comment by amiyasahu** [comment]
Can you raise a bug here - https://github.com/q2a/question2answer/issues 
I will try to fix this issue in q2a core . 

As this plugin is deprecated and not supported any more .

**Comment by palatinuse** [comment]
Done:
https://github.com/q2a/question2answer/issues/300

**Comment by amiyasahu** [comment]
Thanks
